### PR TITLE
Initial addition to the repo

### PR DESCRIPTION
**Pull request by smohid26**
Practice commit. Deleted description from README

### CODE REVIEW

**Comment by leewujung** [comment]
Maybe instead of deleting the original description (which cannot be merged), you can expand on the README? You can do direct push to create the folder structure with actual files in it. Once you are done with those, list and link the data subfolders in the README with a short description. At that time we can merge this.

**Comment by aditya-uw** [comment]
@leewujung, yeah sorry the plan was that we would initialize the folder structure and the README.md all with this PR. Is that okay? And if so, I should probably ask Shahnaz to change the PR title to better reflect that.

**Comment by leewujung** [comment]
Yes that is fine too!

**Comment by aditya-uw** [comment]
Cool! And okay I'll let Shahnaz communicate with you in this PR from here on to figure out specific details!

**Review by leewujung — CHANGES_REQUESTED** [review]
@smohid26: Congrats on your first PR! I have a few suggestions:

- I noticed you created this PR from `main` in your fork. Typically we encourage folks to PR from a branch, so that your `main` is also clean.
- README:
   - add a paragraph on what the repo is about, and what the goal is
   - for each folder, explain what it contains
- environment file:
   - rename `bat_env.yml` to `environment.yml`: just so it is easier for others to recognize it immediately
   - you do not use a lot of libraries in your notebook, so your environment file should just contain the ones you use. Learn about how to write an environment file from scratch and do that here. 
- analysis folder:
  - the current script and notebook have the same content. The code is short so I think you can remove `final.py` completely and just revise the notebook.
  - for a notebook usually people do not put all code in the same block. I encourage you to look at some examples in our other repos, e.g. the `echopype-examples` repo to see the usage; also note the explanation text that plays an important role in the notebook -- there's a reason why it is call a "notebook".
  - you imported pandas but used a lot of looping in the main section of the notebook instead of pandas functionality. I suggest that you go over the `pandas` getting started guide and look for other tutorials as well, and use pandas for the counting operations.

I think we we should merge this PR once you address the above items under README and environment file, so please prioritize these changes and request for my review again once you have them committed here. You can then open another PR for just the analysis notebook. Thanks!

**Comment by leewujung** [comment]
I'll merge this now, and @aditya-uw @FXF48-Mila and I will continue the re-organization outline in the above comment.

**Pull request merged**
